/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"

#import "Error.h"
#import "Core.h"
#import "Activity.h"
#import "Payment.h"

@interface CTokenAccess_t : NSObject <NSCoding> {
  Customer_t * __customer;
  NSString * __token;

  BOOL __customer_isset;
  BOOL __token_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=customer, setter=setCustomer:) Customer_t * customer;
@property (nonatomic, retain, getter=token, setter=setToken:) NSString * token;
#endif

- (id) init;
- (id) initWithCustomer: (Customer_t *) customer token: (NSString *) token;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (Customer_t *) customer;
- (void) setCustomer: (Customer_t *) customer;
#endif
- (BOOL) customerIsSet;

#if !__has_feature(objc_arc)
- (NSString *) token;
- (void) setToken: (NSString *) token;
#endif
- (BOOL) tokenIsSet;

@end

@interface CTokenAccessResponse_t : NSObject <NSCoding> {
  CTokenAccess_t * __tokenAccess;

  BOOL __tokenAccess_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=tokenAccess, setter=setTokenAccess:) CTokenAccess_t * tokenAccess;
#endif

- (id) init;
- (id) initWithTokenAccess: (CTokenAccess_t *) tokenAccess;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (CTokenAccess_t *) tokenAccess;
- (void) setTokenAccess: (CTokenAccess_t *) tokenAccess;
#endif
- (BOOL) tokenAccessIsSet;

@end

@interface DealOfferGeoSummariesResponse_t : NSObject <NSCoding> {
  NSMutableArray * __dealOfferGeoSummaries;
  BOOL __fallbackResponse;

  BOOL __dealOfferGeoSummaries_isset;
  BOOL __fallbackResponse_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=dealOfferGeoSummaries, setter=setDealOfferGeoSummaries:) NSMutableArray * dealOfferGeoSummaries;
@property (nonatomic, getter=fallbackResponse, setter=setFallbackResponse:) BOOL fallbackResponse;
#endif

- (id) init;
- (id) initWithDealOfferGeoSummaries: (NSMutableArray *) dealOfferGeoSummaries fallbackResponse: (BOOL) fallbackResponse;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSMutableArray *) dealOfferGeoSummaries;
- (void) setDealOfferGeoSummaries: (NSMutableArray *) dealOfferGeoSummaries;
#endif
- (BOOL) dealOfferGeoSummariesIsSet;

#if !__has_feature(objc_arc)
- (BOOL) fallbackResponse;
- (void) setFallbackResponse: (BOOL) fallbackResponse;
#endif
- (BOOL) fallbackResponseIsSet;

@end

@interface MerchantsResponse_t : NSObject <NSCoding> {
  NSMutableArray * __merchants;

  BOOL __merchants_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=merchants, setter=setMerchants:) NSMutableArray * merchants;
#endif

- (id) init;
- (id) initWithMerchants: (NSMutableArray *) merchants;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSMutableArray *) merchants;
- (void) setMerchants: (NSMutableArray *) merchants;
#endif
- (BOOL) merchantsIsSet;

@end

@interface ValidateCodeResponse_t : NSObject <NSCoding> {
  BOOL __valid;
  NSString * __codeType;

  BOOL __valid_isset;
  BOOL __codeType_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=valid, setter=setValid:) BOOL valid;
@property (nonatomic, retain, getter=codeType, setter=setCodeType:) NSString * codeType;
#endif

- (id) init;
- (id) initWithValid: (BOOL) valid codeType: (NSString *) codeType;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (BOOL) valid;
- (void) setValid: (BOOL) valid;
#endif
- (BOOL) validIsSet;

#if !__has_feature(objc_arc)
- (NSString *) codeType;
- (void) setCodeType: (NSString *) codeType;
#endif
- (BOOL) codeTypeIsSet;

@end

@interface EmailBodyResponse_t : NSObject <NSCoding> {
  NSString * __emailBody;

  BOOL __emailBody_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=emailBody, setter=setEmailBody:) NSString * emailBody;
#endif

- (id) init;
- (id) initWithEmailBody: (NSString *) emailBody;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSString *) emailBody;
- (void) setEmailBody: (NSString *) emailBody;
#endif
- (BOOL) emailBodyIsSet;

@end

@protocol CustomerService_t <NSObject>
- (CTokenAccess_t *) createAccount: (Customer_t *) customer password: (NSString *) password;  // throws ServiceException_t *, TException
- (CTokenAccess_t *) authenticate: (NSString *) email password: (NSString *) password;  // throws ServiceException_t *, TException
- (BOOL) customerEmailExists: (NSString *) email;  // throws ServiceException_t *, TException
- (void) addSocialAccount: (SocialAccount_t *) socialAccount;  // throws ServiceException_t *, TException
- (void) removeSocialAccount: (int) socialNetwork;  // throws ServiceException_t *, TException
- (NSMutableArray *) getMerchantAcquires: (SearchOptions_t *) searchOptions;  // throws ServiceException_t *, TException
- (NSMutableArray *) getMerchantAcquiresWithLocation: (SearchOptions_t *) searchOptions location: (Location_t *) location;  // throws ServiceException_t *, TException
- (NSMutableArray *) getMerchantAcquiresByCategory: (int32_t) categoryId searchOptions: (SearchOptions_t *) searchOptions;  // throws ServiceException_t *, TException
- (NSMutableArray *) getDealAcquires: (NSString *) merchantId searchOptions: (SearchOptions_t *) searchOptions;  // throws ServiceException_t *, TException
- (NSString *) redeem: (NSString *) dealAcquireId location: (Location_t *) location;  // throws ServiceException_t *, TException
- (NSMutableArray *) getDealOffers;  // throws ServiceException_t *, TException
- (void) activateCode: (NSString *) dealOfferid code: (NSString *) code;  // throws ServiceException_t *, TException
- (DealOffer_t *) getDealOffer: (NSString *) dealOfferId;  // throws ServiceException_t *, TException
- (NSMutableArray *) getDealsByDealOfferId: (NSString *) dealOfferId searchOptions: (SearchOptions_t *) searchOptions;  // throws ServiceException_t *, TException
- (void) purchaseDealOffer: (NSString *) dealOfferId;  // throws ServiceException_t *, TException
- (NSMutableArray *) getMerchantsWithin: (Location_t *) location maxMiles: (int32_t) maxMiles searchOptions: (SearchOptions_t *) searchOptions;  // throws ServiceException_t *, TException
- (void) addFavoriteMerchant: (NSString *) merchantId;  // throws ServiceException_t *, TException
- (void) removeFavoriteMerchant: (NSString *) merchantId;  // throws ServiceException_t *, TException
- (NSMutableArray *) getFavoriteMerchants: (SearchOptions_t *) searchOptions;  // throws ServiceException_t *, TException
- (NSMutableArray *) getCategories;  // throws ServiceException_t *, TException
- (NSString *) giftToFacebook: (NSString *) dealAcquireId facebookId: (NSString *) facebookId receipientName: (NSString *) receipientName;  // throws ServiceException_t *, TException
- (NSString *) giftToEmail: (NSString *) dealAcquireId email: (NSString *) email receipientName: (NSString *) receipientName;  // throws ServiceException_t *, TException
- (Gift_t *) getGift: (NSString *) giftId;  // throws ServiceException_t *, TException
- (DealAcquire_t *) acceptGift: (NSString *) giftId;  // throws ServiceException_t *, TException
- (void) rejectGift: (NSString *) giftId;  // throws ServiceException_t *, TException
- (NSMutableArray *) getActivities: (SearchOptions_t *) searchOptions;  // throws ServiceException_t *, TException
- (NSMutableArray *) getMessages: (SearchOptions_t *) searchOptions location: (Location_t *) location;  // throws ServiceException_t *, TException
- (void) activityAction: (NSString *) activityId;  // throws ServiceException_t *, TException
- (void) sendResetPasswordEmail: (NSString *) email;  // throws TServiceException_t *, TUserException_t *, TNotFoundException_t *, TException
- (CTokenAccess_t *) resetPassword: (NSString *) customerId resetPasswordCode: (NSString *) resetPasswordCode newPassword: (NSString *) newPassword;  // throws TServiceException_t *, TUserException_t *, TNotFoundException_t *, TException
- (TransactionResult_t *) purchaseByCard: (NSString *) dealOfferId paymentDetail: (PaymentDetail_t *) paymentDetail;  // throws TServiceException_t *, TUserException_t *, TNotFoundException_t *, TException
- (TransactionResult_t *) purchaseByCode: (NSString *) dealOfferId paymentCode: (NSString *) paymentCode;  // throws TServiceException_t *, TUserException_t *, TNotFoundException_t *, TException
- (CTokenAccessResponse_t *) loginFacebook: (NSString *) facebookId facebookAccessToken: (NSString *) facebookAccessToken;  // throws TServiceException_t *, TException
- (DealOfferGeoSummariesResponse_t *) getDealOfferGeoSummariesWithin: (Location_t *) location maxMiles: (int32_t) maxMiles searchOptions: (SearchOptions_t *) searchOptions fallbackSearchOptions: (SearchOptions_t *) fallbackSearchOptions;  // throws TServiceException_t *, TException
- (MerchantsResponse_t *) getMerchantsByDealOfferId: (NSString *) dealOfferId searchOptions: (SearchOptions_t *) searchOptions;  // throws ServiceException_t *, TException
- (ValidateCodeResponse_t *) validateCode: (NSString *) code dealOfferId: (NSString *) dealOfferId;  // throws TServiceException_t *, TException
- (TransactionResult_t *) purchaseWithCard: (NSString *) dealOfferId paymentDetail: (PaymentDetail_t *) paymentDetail paymentProperties: (NSMutableDictionary *) paymentProperties;  // throws TServiceException_t *, TUserException_t *, TNotFoundException_t *, TException
- (TransactionResult_t *) purchaseWithCode: (NSString *) dealOfferId paymentCode: (NSString *) paymentCode paymentProperties: (NSMutableDictionary *) paymentProperties;  // throws TServiceException_t *, TUserException_t *, TNotFoundException_t *, TException
- (EmailBodyResponse_t *) getEmailBody: (NSString *) templateId entityId: (NSString *) entityId;  // throws TServiceException_t *, TException
@end

@interface CustomerService_tClient : NSObject <CustomerService_t> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface CustomerService_tProcessor : NSObject <TProcessor> {
  id <CustomerService_t> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithCustomerService_t: (id <CustomerService_t>) service;
- (id<CustomerService_t>) service;
@end

@interface CustomerServiceConstants : NSObject {
}
+ (NSString *) CTOKEN_NAME;
@end
