/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"


enum ErrorCode_t {
  ErrorCode_t_UNKNOWN = 0,
  ErrorCode_t_VALID_EMAIL_REQUIRED = 100,
  ErrorCode_t_PASS_REQUIRED = 101,
  ErrorCode_t_PASS_CONFIRM_MUST_MATCH = 102,
  ErrorCode_t_PASS_RESET_CODE_REQUIRED = 103,
  ErrorCode_t_PASS_RESET_CODE_EXPIRED = 104,
  ErrorCode_t_PASS_RESET_CODE_INVALID = 105,
  ErrorCode_t_EMAIL_ALREADY_TAKEN = 1000,
  ErrorCode_t_INVALID_USERNAME_OR_PASSWORD = 1001,
  ErrorCode_t_CUSTOMER_DOES_NOT_OWN_DEAL = 1002,
  ErrorCode_t_DEAL_ALREADY_REDEEMED = 1003,
  ErrorCode_t_GIFTING_NOT_ALLOWED1 = 1004,
  ErrorCode_t_CUSTOMER_NOT_FOUND = 1005,
  ErrorCode_t_EMAIL_REQUIRED = 1006,
  ErrorCode_t_MAIL_TEMPLATE_NOT_FOUND = 2004,
  ErrorCode_t_ACTIVIATION_CODE_NOT_FOUND = 3000,
  ErrorCode_t_ACTIVIATION_CODE_ALREADY_ACTIVATED = 3001
};

@interface TServiceException_t : NSException <NSCoding> {
  int __errorCode;
  NSString * __message;

  BOOL __errorCode_isset;
  BOOL __message_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int errorCode;
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
#endif

- (id) init;
- (id) initWithErrorCode: (int) errorCode message: (NSString *) message;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (int) errorCode;
- (void) setErrorCode: (int) errorCode;
#endif
- (BOOL) errorCodeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

@end

@interface TUserException_t : NSException <NSCoding> {
  int __errorCode;
  NSString * __param;

  BOOL __errorCode_isset;
  BOOL __param_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int errorCode;
@property (nonatomic, retain, getter=param, setter=setParam:) NSString * param;
#endif

- (id) init;
- (id) initWithErrorCode: (int) errorCode param: (NSString *) param;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (int) errorCode;
- (void) setErrorCode: (int) errorCode;
#endif
- (BOOL) errorCodeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) param;
- (void) setParam: (NSString *) param;
#endif
- (BOOL) paramIsSet;

@end

@interface TNotFoundException_t : NSException <NSCoding> {
  NSString * __identifier;
  NSString * __key;

  BOOL __identifier_isset;
  BOOL __key_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=identifier, setter=setIdentifier:) NSString * identifier;
@property (nonatomic, retain, getter=key, setter=setKey:) NSString * key;
#endif

- (id) init;
- (id) initWithIdentifier: (NSString *) identifier key: (NSString *) key;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSString *) identifier;
- (void) setIdentifier: (NSString *) identifier;
#endif
- (BOOL) identifierIsSet;

#if !__has_feature(objc_arc)
- (NSString *) key;
- (void) setKey: (NSString *) key;
#endif
- (BOOL) keyIsSet;

@end

@interface ErrorConstants : NSObject {
}
@end
