/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


#import "Property.h"

static NSString * FUNDRAISING_BOOK = @"fundraising_book";
static NSString * SUBSCRIPTION = @"subscription";
static NSString * MERCHANT_CODE = @"merchant_code";
static NSString * ACTIVATION_CODE = @"activation_code";
static NSString * TEMPLATE_ID = @"template_id";

@implementation PropertyConstants
+ (void) initialize {
}
+ (NSString *) FUNDRAISING_BOOK{
  return FUNDRAISING_BOOK;
}
+ (NSString *) SUBSCRIPTION{
  return SUBSCRIPTION;
}
+ (NSString *) MERCHANT_CODE{
  return MERCHANT_CODE;
}
+ (NSString *) ACTIVATION_CODE{
  return ACTIVATION_CODE;
}
+ (NSString *) TEMPLATE_ID{
  return TEMPLATE_ID;
}
@end

