/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


@interface PropertyConstants : NSObject {
}
+ (NSString *) FUNDRAISING_BOOK;
+ (NSString *) SUBSCRIPTION;
+ (NSString *) MERCHANT_CODE;
+ (NSString *) ACTIVATION_CODE;
+ (NSString *) TEMPLATE_ID;
@end
