/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"


#import "Property.h"

static NSString * FUNDRAISING_BOOK = @"fundraising_book";
static NSString * SUBSCRIPTION = @"subscription";

@implementation PropertyConstants
+ (void) initialize {
}
+ (NSString *) FUNDRAISING_BOOK{
  return FUNDRAISING_BOOK;
}
+ (NSString *) SUBSCRIPTION{
  return SUBSCRIPTION;
}
@end

