/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.talool.api.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ActivityEvent_t implements org.apache.thrift.TEnum {
  UNKNOWN(0),
  PURCHASE(1),
  REDEEM(2),
  REJECT_GIFT(3),
  FACEBOOK_RECV_GIFT(4),
  FACEBOOK_SEND_GIFT(5),
  EMAIL_RECV_GIFT(6),
  EMAIL_SEND_GIFT(7),
  FRIEND_GIFT_ACCEPT(8),
  FRIEND_GIFT_REJECT(9),
  FRIEND_GIFT_REDEEM(10),
  FRIEND_PURCHASE_DEAL_OFFER(11),
  MERCHANT_REACH(12),
  TALOOL_REACH(13),
  AD(14);

  private final int value;

  private ActivityEvent_t(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ActivityEvent_t findByValue(int value) { 
    switch (value) {
      case 0:
        return UNKNOWN;
      case 1:
        return PURCHASE;
      case 2:
        return REDEEM;
      case 3:
        return REJECT_GIFT;
      case 4:
        return FACEBOOK_RECV_GIFT;
      case 5:
        return FACEBOOK_SEND_GIFT;
      case 6:
        return EMAIL_RECV_GIFT;
      case 7:
        return EMAIL_SEND_GIFT;
      case 8:
        return FRIEND_GIFT_ACCEPT;
      case 9:
        return FRIEND_GIFT_REJECT;
      case 10:
        return FRIEND_GIFT_REDEEM;
      case 11:
        return FRIEND_PURCHASE_DEAL_OFFER;
      case 12:
        return MERCHANT_REACH;
      case 13:
        return TALOOL_REACH;
      case 14:
        return AD;
      default:
        return null;
    }
  }
}
