/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.talool.api.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class DealOfferGeoSummariesResponse_t implements org.apache.thrift.TBase<DealOfferGeoSummariesResponse_t, DealOfferGeoSummariesResponse_t._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DealOfferGeoSummariesResponse_t");

  private static final org.apache.thrift.protocol.TField DEAL_OFFER_GEO_SUMMARIES_FIELD_DESC = new org.apache.thrift.protocol.TField("dealOfferGeoSummaries", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField FALLBACK_RESPONSE_FIELD_DESC = new org.apache.thrift.protocol.TField("fallbackResponse", org.apache.thrift.protocol.TType.BOOL, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new DealOfferGeoSummariesResponse_tStandardSchemeFactory());
    schemes.put(TupleScheme.class, new DealOfferGeoSummariesResponse_tTupleSchemeFactory());
  }

  public List<com.talool.api.thrift.DealOfferGeoSummary_t> dealOfferGeoSummaries; // optional
  public boolean fallbackResponse; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    DEAL_OFFER_GEO_SUMMARIES((short)1, "dealOfferGeoSummaries"),
    FALLBACK_RESPONSE((short)2, "fallbackResponse");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DEAL_OFFER_GEO_SUMMARIES
          return DEAL_OFFER_GEO_SUMMARIES;
        case 2: // FALLBACK_RESPONSE
          return FALLBACK_RESPONSE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __FALLBACKRESPONSE_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.DEAL_OFFER_GEO_SUMMARIES};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DEAL_OFFER_GEO_SUMMARIES, new org.apache.thrift.meta_data.FieldMetaData("dealOfferGeoSummaries", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, com.talool.api.thrift.DealOfferGeoSummary_t.class))));
    tmpMap.put(_Fields.FALLBACK_RESPONSE, new org.apache.thrift.meta_data.FieldMetaData("fallbackResponse", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DealOfferGeoSummariesResponse_t.class, metaDataMap);
  }

  public DealOfferGeoSummariesResponse_t() {
  }

  public DealOfferGeoSummariesResponse_t(
    boolean fallbackResponse)
  {
    this();
    this.fallbackResponse = fallbackResponse;
    setFallbackResponseIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DealOfferGeoSummariesResponse_t(DealOfferGeoSummariesResponse_t other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetDealOfferGeoSummaries()) {
      List<com.talool.api.thrift.DealOfferGeoSummary_t> __this__dealOfferGeoSummaries = new ArrayList<com.talool.api.thrift.DealOfferGeoSummary_t>();
      for (com.talool.api.thrift.DealOfferGeoSummary_t other_element : other.dealOfferGeoSummaries) {
        __this__dealOfferGeoSummaries.add(new com.talool.api.thrift.DealOfferGeoSummary_t(other_element));
      }
      this.dealOfferGeoSummaries = __this__dealOfferGeoSummaries;
    }
    this.fallbackResponse = other.fallbackResponse;
  }

  public DealOfferGeoSummariesResponse_t deepCopy() {
    return new DealOfferGeoSummariesResponse_t(this);
  }

  public void clear() {
    this.dealOfferGeoSummaries = null;
    setFallbackResponseIsSet(false);
    this.fallbackResponse = false;
  }

  public int getDealOfferGeoSummariesSize() {
    return (this.dealOfferGeoSummaries == null) ? 0 : this.dealOfferGeoSummaries.size();
  }

  public java.util.Iterator<com.talool.api.thrift.DealOfferGeoSummary_t> getDealOfferGeoSummariesIterator() {
    return (this.dealOfferGeoSummaries == null) ? null : this.dealOfferGeoSummaries.iterator();
  }

  public void addToDealOfferGeoSummaries(com.talool.api.thrift.DealOfferGeoSummary_t elem) {
    if (this.dealOfferGeoSummaries == null) {
      this.dealOfferGeoSummaries = new ArrayList<com.talool.api.thrift.DealOfferGeoSummary_t>();
    }
    this.dealOfferGeoSummaries.add(elem);
  }

  public List<com.talool.api.thrift.DealOfferGeoSummary_t> getDealOfferGeoSummaries() {
    return this.dealOfferGeoSummaries;
  }

  public DealOfferGeoSummariesResponse_t setDealOfferGeoSummaries(List<com.talool.api.thrift.DealOfferGeoSummary_t> dealOfferGeoSummaries) {
    this.dealOfferGeoSummaries = dealOfferGeoSummaries;
    return this;
  }

  public void unsetDealOfferGeoSummaries() {
    this.dealOfferGeoSummaries = null;
  }

  /** Returns true if field dealOfferGeoSummaries is set (has been assigned a value) and false otherwise */
  public boolean isSetDealOfferGeoSummaries() {
    return this.dealOfferGeoSummaries != null;
  }

  public void setDealOfferGeoSummariesIsSet(boolean value) {
    if (!value) {
      this.dealOfferGeoSummaries = null;
    }
  }

  public boolean isFallbackResponse() {
    return this.fallbackResponse;
  }

  public DealOfferGeoSummariesResponse_t setFallbackResponse(boolean fallbackResponse) {
    this.fallbackResponse = fallbackResponse;
    setFallbackResponseIsSet(true);
    return this;
  }

  public void unsetFallbackResponse() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __FALLBACKRESPONSE_ISSET_ID);
  }

  /** Returns true if field fallbackResponse is set (has been assigned a value) and false otherwise */
  public boolean isSetFallbackResponse() {
    return EncodingUtils.testBit(__isset_bitfield, __FALLBACKRESPONSE_ISSET_ID);
  }

  public void setFallbackResponseIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __FALLBACKRESPONSE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case DEAL_OFFER_GEO_SUMMARIES:
      if (value == null) {
        unsetDealOfferGeoSummaries();
      } else {
        setDealOfferGeoSummaries((List<com.talool.api.thrift.DealOfferGeoSummary_t>)value);
      }
      break;

    case FALLBACK_RESPONSE:
      if (value == null) {
        unsetFallbackResponse();
      } else {
        setFallbackResponse((Boolean)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case DEAL_OFFER_GEO_SUMMARIES:
      return getDealOfferGeoSummaries();

    case FALLBACK_RESPONSE:
      return Boolean.valueOf(isFallbackResponse());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case DEAL_OFFER_GEO_SUMMARIES:
      return isSetDealOfferGeoSummaries();
    case FALLBACK_RESPONSE:
      return isSetFallbackResponse();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof DealOfferGeoSummariesResponse_t)
      return this.equals((DealOfferGeoSummariesResponse_t)that);
    return false;
  }

  public boolean equals(DealOfferGeoSummariesResponse_t that) {
    if (that == null)
      return false;

    boolean this_present_dealOfferGeoSummaries = true && this.isSetDealOfferGeoSummaries();
    boolean that_present_dealOfferGeoSummaries = true && that.isSetDealOfferGeoSummaries();
    if (this_present_dealOfferGeoSummaries || that_present_dealOfferGeoSummaries) {
      if (!(this_present_dealOfferGeoSummaries && that_present_dealOfferGeoSummaries))
        return false;
      if (!this.dealOfferGeoSummaries.equals(that.dealOfferGeoSummaries))
        return false;
    }

    boolean this_present_fallbackResponse = true;
    boolean that_present_fallbackResponse = true;
    if (this_present_fallbackResponse || that_present_fallbackResponse) {
      if (!(this_present_fallbackResponse && that_present_fallbackResponse))
        return false;
      if (this.fallbackResponse != that.fallbackResponse)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(DealOfferGeoSummariesResponse_t other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    DealOfferGeoSummariesResponse_t typedOther = (DealOfferGeoSummariesResponse_t)other;

    lastComparison = Boolean.valueOf(isSetDealOfferGeoSummaries()).compareTo(typedOther.isSetDealOfferGeoSummaries());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDealOfferGeoSummaries()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dealOfferGeoSummaries, typedOther.dealOfferGeoSummaries);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFallbackResponse()).compareTo(typedOther.isSetFallbackResponse());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFallbackResponse()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fallbackResponse, typedOther.fallbackResponse);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("DealOfferGeoSummariesResponse_t(");
    boolean first = true;

    if (isSetDealOfferGeoSummaries()) {
      sb.append("dealOfferGeoSummaries:");
      if (this.dealOfferGeoSummaries == null) {
        sb.append("null");
      } else {
        sb.append(this.dealOfferGeoSummaries);
      }
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("fallbackResponse:");
    sb.append(this.fallbackResponse);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'fallbackResponse' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te.getMessage());
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te.getMessage());
    }
  }

  private static class DealOfferGeoSummariesResponse_tStandardSchemeFactory implements SchemeFactory {
    public DealOfferGeoSummariesResponse_tStandardScheme getScheme() {
      return new DealOfferGeoSummariesResponse_tStandardScheme();
    }
  }

  private static class DealOfferGeoSummariesResponse_tStandardScheme extends StandardScheme<DealOfferGeoSummariesResponse_t> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, DealOfferGeoSummariesResponse_t struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DEAL_OFFER_GEO_SUMMARIES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.dealOfferGeoSummaries = new ArrayList<com.talool.api.thrift.DealOfferGeoSummary_t>(_list0.size);
                for (int _i1 = 0; _i1 < _list0.size; ++_i1)
                {
                  com.talool.api.thrift.DealOfferGeoSummary_t _elem2; // required
                  _elem2 = new com.talool.api.thrift.DealOfferGeoSummary_t();
                  _elem2.read(iprot);
                  struct.dealOfferGeoSummaries.add(_elem2);
                }
                iprot.readListEnd();
              }
              struct.setDealOfferGeoSummariesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // FALLBACK_RESPONSE
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.fallbackResponse = iprot.readBool();
              struct.setFallbackResponseIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetFallbackResponse()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'fallbackResponse' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, DealOfferGeoSummariesResponse_t struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.dealOfferGeoSummaries != null) {
        if (struct.isSetDealOfferGeoSummaries()) {
          oprot.writeFieldBegin(DEAL_OFFER_GEO_SUMMARIES_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.dealOfferGeoSummaries.size()));
            for (com.talool.api.thrift.DealOfferGeoSummary_t _iter3 : struct.dealOfferGeoSummaries)
            {
              _iter3.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldBegin(FALLBACK_RESPONSE_FIELD_DESC);
      oprot.writeBool(struct.fallbackResponse);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DealOfferGeoSummariesResponse_tTupleSchemeFactory implements SchemeFactory {
    public DealOfferGeoSummariesResponse_tTupleScheme getScheme() {
      return new DealOfferGeoSummariesResponse_tTupleScheme();
    }
  }

  private static class DealOfferGeoSummariesResponse_tTupleScheme extends TupleScheme<DealOfferGeoSummariesResponse_t> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, DealOfferGeoSummariesResponse_t struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeBool(struct.fallbackResponse);
      BitSet optionals = new BitSet();
      if (struct.isSetDealOfferGeoSummaries()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetDealOfferGeoSummaries()) {
        {
          oprot.writeI32(struct.dealOfferGeoSummaries.size());
          for (com.talool.api.thrift.DealOfferGeoSummary_t _iter4 : struct.dealOfferGeoSummaries)
          {
            _iter4.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, DealOfferGeoSummariesResponse_t struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.fallbackResponse = iprot.readBool();
      struct.setFallbackResponseIsSet(true);
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.dealOfferGeoSummaries = new ArrayList<com.talool.api.thrift.DealOfferGeoSummary_t>(_list5.size);
          for (int _i6 = 0; _i6 < _list5.size; ++_i6)
          {
            com.talool.api.thrift.DealOfferGeoSummary_t _elem7; // required
            _elem7 = new com.talool.api.thrift.DealOfferGeoSummary_t();
            _elem7.read(iprot);
            struct.dealOfferGeoSummaries.add(_elem7);
          }
        }
        struct.setDealOfferGeoSummariesIsSet(true);
      }
    }
  }

}

