/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.talool.api.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class DealOfferGeoSummary_t implements org.apache.thrift.TBase<DealOfferGeoSummary_t, DealOfferGeoSummary_t._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DealOfferGeoSummary_t");

  private static final org.apache.thrift.protocol.TField DEAL_OFFER_FIELD_DESC = new org.apache.thrift.protocol.TField("dealOffer", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField DISTANCE_IN_METERS_FIELD_DESC = new org.apache.thrift.protocol.TField("distanceInMeters", org.apache.thrift.protocol.TType.DOUBLE, (short)2);
  private static final org.apache.thrift.protocol.TField CLOSEST_MERCHANT_IN_METERS_FIELD_DESC = new org.apache.thrift.protocol.TField("closestMerchantInMeters", org.apache.thrift.protocol.TType.DOUBLE, (short)3);
  private static final org.apache.thrift.protocol.TField DOUBLE_METRICS_FIELD_DESC = new org.apache.thrift.protocol.TField("doubleMetrics", org.apache.thrift.protocol.TType.MAP, (short)4);
  private static final org.apache.thrift.protocol.TField LONG_METRICS_FIELD_DESC = new org.apache.thrift.protocol.TField("longMetrics", org.apache.thrift.protocol.TType.MAP, (short)5);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new DealOfferGeoSummary_tStandardSchemeFactory());
    schemes.put(TupleScheme.class, new DealOfferGeoSummary_tTupleSchemeFactory());
  }

  public DealOffer_t dealOffer; // required
  public double distanceInMeters; // optional
  public double closestMerchantInMeters; // optional
  public Map<String,Double> doubleMetrics; // optional
  public Map<String,Long> longMetrics; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    DEAL_OFFER((short)1, "dealOffer"),
    DISTANCE_IN_METERS((short)2, "distanceInMeters"),
    CLOSEST_MERCHANT_IN_METERS((short)3, "closestMerchantInMeters"),
    DOUBLE_METRICS((short)4, "doubleMetrics"),
    LONG_METRICS((short)5, "longMetrics");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DEAL_OFFER
          return DEAL_OFFER;
        case 2: // DISTANCE_IN_METERS
          return DISTANCE_IN_METERS;
        case 3: // CLOSEST_MERCHANT_IN_METERS
          return CLOSEST_MERCHANT_IN_METERS;
        case 4: // DOUBLE_METRICS
          return DOUBLE_METRICS;
        case 5: // LONG_METRICS
          return LONG_METRICS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __DISTANCEINMETERS_ISSET_ID = 0;
  private static final int __CLOSESTMERCHANTINMETERS_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.DISTANCE_IN_METERS,_Fields.CLOSEST_MERCHANT_IN_METERS,_Fields.DOUBLE_METRICS,_Fields.LONG_METRICS};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DEAL_OFFER, new org.apache.thrift.meta_data.FieldMetaData("dealOffer", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, DealOffer_t.class)));
    tmpMap.put(_Fields.DISTANCE_IN_METERS, new org.apache.thrift.meta_data.FieldMetaData("distanceInMeters", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.CLOSEST_MERCHANT_IN_METERS, new org.apache.thrift.meta_data.FieldMetaData("closestMerchantInMeters", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.DOUBLE_METRICS, new org.apache.thrift.meta_data.FieldMetaData("doubleMetrics", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE))));
    tmpMap.put(_Fields.LONG_METRICS, new org.apache.thrift.meta_data.FieldMetaData("longMetrics", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DealOfferGeoSummary_t.class, metaDataMap);
  }

  public DealOfferGeoSummary_t() {
  }

  public DealOfferGeoSummary_t(
    DealOffer_t dealOffer)
  {
    this();
    this.dealOffer = dealOffer;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DealOfferGeoSummary_t(DealOfferGeoSummary_t other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetDealOffer()) {
      this.dealOffer = new DealOffer_t(other.dealOffer);
    }
    this.distanceInMeters = other.distanceInMeters;
    this.closestMerchantInMeters = other.closestMerchantInMeters;
    if (other.isSetDoubleMetrics()) {
      Map<String,Double> __this__doubleMetrics = new HashMap<String,Double>();
      for (Map.Entry<String, Double> other_element : other.doubleMetrics.entrySet()) {

        String other_element_key = other_element.getKey();
        Double other_element_value = other_element.getValue();

        String __this__doubleMetrics_copy_key = other_element_key;

        Double __this__doubleMetrics_copy_value = other_element_value;

        __this__doubleMetrics.put(__this__doubleMetrics_copy_key, __this__doubleMetrics_copy_value);
      }
      this.doubleMetrics = __this__doubleMetrics;
    }
    if (other.isSetLongMetrics()) {
      Map<String,Long> __this__longMetrics = new HashMap<String,Long>();
      for (Map.Entry<String, Long> other_element : other.longMetrics.entrySet()) {

        String other_element_key = other_element.getKey();
        Long other_element_value = other_element.getValue();

        String __this__longMetrics_copy_key = other_element_key;

        Long __this__longMetrics_copy_value = other_element_value;

        __this__longMetrics.put(__this__longMetrics_copy_key, __this__longMetrics_copy_value);
      }
      this.longMetrics = __this__longMetrics;
    }
  }

  public DealOfferGeoSummary_t deepCopy() {
    return new DealOfferGeoSummary_t(this);
  }

  public void clear() {
    this.dealOffer = null;
    setDistanceInMetersIsSet(false);
    this.distanceInMeters = 0.0;
    setClosestMerchantInMetersIsSet(false);
    this.closestMerchantInMeters = 0.0;
    this.doubleMetrics = null;
    this.longMetrics = null;
  }

  public DealOffer_t getDealOffer() {
    return this.dealOffer;
  }

  public DealOfferGeoSummary_t setDealOffer(DealOffer_t dealOffer) {
    this.dealOffer = dealOffer;
    return this;
  }

  public void unsetDealOffer() {
    this.dealOffer = null;
  }

  /** Returns true if field dealOffer is set (has been assigned a value) and false otherwise */
  public boolean isSetDealOffer() {
    return this.dealOffer != null;
  }

  public void setDealOfferIsSet(boolean value) {
    if (!value) {
      this.dealOffer = null;
    }
  }

  public double getDistanceInMeters() {
    return this.distanceInMeters;
  }

  public DealOfferGeoSummary_t setDistanceInMeters(double distanceInMeters) {
    this.distanceInMeters = distanceInMeters;
    setDistanceInMetersIsSet(true);
    return this;
  }

  public void unsetDistanceInMeters() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __DISTANCEINMETERS_ISSET_ID);
  }

  /** Returns true if field distanceInMeters is set (has been assigned a value) and false otherwise */
  public boolean isSetDistanceInMeters() {
    return EncodingUtils.testBit(__isset_bitfield, __DISTANCEINMETERS_ISSET_ID);
  }

  public void setDistanceInMetersIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __DISTANCEINMETERS_ISSET_ID, value);
  }

  public double getClosestMerchantInMeters() {
    return this.closestMerchantInMeters;
  }

  public DealOfferGeoSummary_t setClosestMerchantInMeters(double closestMerchantInMeters) {
    this.closestMerchantInMeters = closestMerchantInMeters;
    setClosestMerchantInMetersIsSet(true);
    return this;
  }

  public void unsetClosestMerchantInMeters() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __CLOSESTMERCHANTINMETERS_ISSET_ID);
  }

  /** Returns true if field closestMerchantInMeters is set (has been assigned a value) and false otherwise */
  public boolean isSetClosestMerchantInMeters() {
    return EncodingUtils.testBit(__isset_bitfield, __CLOSESTMERCHANTINMETERS_ISSET_ID);
  }

  public void setClosestMerchantInMetersIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __CLOSESTMERCHANTINMETERS_ISSET_ID, value);
  }

  public int getDoubleMetricsSize() {
    return (this.doubleMetrics == null) ? 0 : this.doubleMetrics.size();
  }

  public void putToDoubleMetrics(String key, double val) {
    if (this.doubleMetrics == null) {
      this.doubleMetrics = new HashMap<String,Double>();
    }
    this.doubleMetrics.put(key, val);
  }

  public Map<String,Double> getDoubleMetrics() {
    return this.doubleMetrics;
  }

  public DealOfferGeoSummary_t setDoubleMetrics(Map<String,Double> doubleMetrics) {
    this.doubleMetrics = doubleMetrics;
    return this;
  }

  public void unsetDoubleMetrics() {
    this.doubleMetrics = null;
  }

  /** Returns true if field doubleMetrics is set (has been assigned a value) and false otherwise */
  public boolean isSetDoubleMetrics() {
    return this.doubleMetrics != null;
  }

  public void setDoubleMetricsIsSet(boolean value) {
    if (!value) {
      this.doubleMetrics = null;
    }
  }

  public int getLongMetricsSize() {
    return (this.longMetrics == null) ? 0 : this.longMetrics.size();
  }

  public void putToLongMetrics(String key, long val) {
    if (this.longMetrics == null) {
      this.longMetrics = new HashMap<String,Long>();
    }
    this.longMetrics.put(key, val);
  }

  public Map<String,Long> getLongMetrics() {
    return this.longMetrics;
  }

  public DealOfferGeoSummary_t setLongMetrics(Map<String,Long> longMetrics) {
    this.longMetrics = longMetrics;
    return this;
  }

  public void unsetLongMetrics() {
    this.longMetrics = null;
  }

  /** Returns true if field longMetrics is set (has been assigned a value) and false otherwise */
  public boolean isSetLongMetrics() {
    return this.longMetrics != null;
  }

  public void setLongMetricsIsSet(boolean value) {
    if (!value) {
      this.longMetrics = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case DEAL_OFFER:
      if (value == null) {
        unsetDealOffer();
      } else {
        setDealOffer((DealOffer_t)value);
      }
      break;

    case DISTANCE_IN_METERS:
      if (value == null) {
        unsetDistanceInMeters();
      } else {
        setDistanceInMeters((Double)value);
      }
      break;

    case CLOSEST_MERCHANT_IN_METERS:
      if (value == null) {
        unsetClosestMerchantInMeters();
      } else {
        setClosestMerchantInMeters((Double)value);
      }
      break;

    case DOUBLE_METRICS:
      if (value == null) {
        unsetDoubleMetrics();
      } else {
        setDoubleMetrics((Map<String,Double>)value);
      }
      break;

    case LONG_METRICS:
      if (value == null) {
        unsetLongMetrics();
      } else {
        setLongMetrics((Map<String,Long>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case DEAL_OFFER:
      return getDealOffer();

    case DISTANCE_IN_METERS:
      return Double.valueOf(getDistanceInMeters());

    case CLOSEST_MERCHANT_IN_METERS:
      return Double.valueOf(getClosestMerchantInMeters());

    case DOUBLE_METRICS:
      return getDoubleMetrics();

    case LONG_METRICS:
      return getLongMetrics();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case DEAL_OFFER:
      return isSetDealOffer();
    case DISTANCE_IN_METERS:
      return isSetDistanceInMeters();
    case CLOSEST_MERCHANT_IN_METERS:
      return isSetClosestMerchantInMeters();
    case DOUBLE_METRICS:
      return isSetDoubleMetrics();
    case LONG_METRICS:
      return isSetLongMetrics();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof DealOfferGeoSummary_t)
      return this.equals((DealOfferGeoSummary_t)that);
    return false;
  }

  public boolean equals(DealOfferGeoSummary_t that) {
    if (that == null)
      return false;

    boolean this_present_dealOffer = true && this.isSetDealOffer();
    boolean that_present_dealOffer = true && that.isSetDealOffer();
    if (this_present_dealOffer || that_present_dealOffer) {
      if (!(this_present_dealOffer && that_present_dealOffer))
        return false;
      if (!this.dealOffer.equals(that.dealOffer))
        return false;
    }

    boolean this_present_distanceInMeters = true && this.isSetDistanceInMeters();
    boolean that_present_distanceInMeters = true && that.isSetDistanceInMeters();
    if (this_present_distanceInMeters || that_present_distanceInMeters) {
      if (!(this_present_distanceInMeters && that_present_distanceInMeters))
        return false;
      if (this.distanceInMeters != that.distanceInMeters)
        return false;
    }

    boolean this_present_closestMerchantInMeters = true && this.isSetClosestMerchantInMeters();
    boolean that_present_closestMerchantInMeters = true && that.isSetClosestMerchantInMeters();
    if (this_present_closestMerchantInMeters || that_present_closestMerchantInMeters) {
      if (!(this_present_closestMerchantInMeters && that_present_closestMerchantInMeters))
        return false;
      if (this.closestMerchantInMeters != that.closestMerchantInMeters)
        return false;
    }

    boolean this_present_doubleMetrics = true && this.isSetDoubleMetrics();
    boolean that_present_doubleMetrics = true && that.isSetDoubleMetrics();
    if (this_present_doubleMetrics || that_present_doubleMetrics) {
      if (!(this_present_doubleMetrics && that_present_doubleMetrics))
        return false;
      if (!this.doubleMetrics.equals(that.doubleMetrics))
        return false;
    }

    boolean this_present_longMetrics = true && this.isSetLongMetrics();
    boolean that_present_longMetrics = true && that.isSetLongMetrics();
    if (this_present_longMetrics || that_present_longMetrics) {
      if (!(this_present_longMetrics && that_present_longMetrics))
        return false;
      if (!this.longMetrics.equals(that.longMetrics))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(DealOfferGeoSummary_t other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    DealOfferGeoSummary_t typedOther = (DealOfferGeoSummary_t)other;

    lastComparison = Boolean.valueOf(isSetDealOffer()).compareTo(typedOther.isSetDealOffer());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDealOffer()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dealOffer, typedOther.dealOffer);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDistanceInMeters()).compareTo(typedOther.isSetDistanceInMeters());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDistanceInMeters()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.distanceInMeters, typedOther.distanceInMeters);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetClosestMerchantInMeters()).compareTo(typedOther.isSetClosestMerchantInMeters());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetClosestMerchantInMeters()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.closestMerchantInMeters, typedOther.closestMerchantInMeters);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDoubleMetrics()).compareTo(typedOther.isSetDoubleMetrics());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDoubleMetrics()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.doubleMetrics, typedOther.doubleMetrics);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLongMetrics()).compareTo(typedOther.isSetLongMetrics());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLongMetrics()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.longMetrics, typedOther.longMetrics);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("DealOfferGeoSummary_t(");
    boolean first = true;

    sb.append("dealOffer:");
    if (this.dealOffer == null) {
      sb.append("null");
    } else {
      sb.append(this.dealOffer);
    }
    first = false;
    if (isSetDistanceInMeters()) {
      if (!first) sb.append(", ");
      sb.append("distanceInMeters:");
      sb.append(this.distanceInMeters);
      first = false;
    }
    if (isSetClosestMerchantInMeters()) {
      if (!first) sb.append(", ");
      sb.append("closestMerchantInMeters:");
      sb.append(this.closestMerchantInMeters);
      first = false;
    }
    if (isSetDoubleMetrics()) {
      if (!first) sb.append(", ");
      sb.append("doubleMetrics:");
      if (this.doubleMetrics == null) {
        sb.append("null");
      } else {
        sb.append(this.doubleMetrics);
      }
      first = false;
    }
    if (isSetLongMetrics()) {
      if (!first) sb.append(", ");
      sb.append("longMetrics:");
      if (this.longMetrics == null) {
        sb.append("null");
      } else {
        sb.append(this.longMetrics);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (dealOffer == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'dealOffer' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (dealOffer != null) {
      dealOffer.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te.getMessage());
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te.getMessage());
    }
  }

  private static class DealOfferGeoSummary_tStandardSchemeFactory implements SchemeFactory {
    public DealOfferGeoSummary_tStandardScheme getScheme() {
      return new DealOfferGeoSummary_tStandardScheme();
    }
  }

  private static class DealOfferGeoSummary_tStandardScheme extends StandardScheme<DealOfferGeoSummary_t> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, DealOfferGeoSummary_t struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DEAL_OFFER
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.dealOffer = new DealOffer_t();
              struct.dealOffer.read(iprot);
              struct.setDealOfferIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DISTANCE_IN_METERS
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.distanceInMeters = iprot.readDouble();
              struct.setDistanceInMetersIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // CLOSEST_MERCHANT_IN_METERS
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.closestMerchantInMeters = iprot.readDouble();
              struct.setClosestMerchantInMetersIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // DOUBLE_METRICS
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map18 = iprot.readMapBegin();
                struct.doubleMetrics = new HashMap<String,Double>(2*_map18.size);
                for (int _i19 = 0; _i19 < _map18.size; ++_i19)
                {
                  String _key20; // required
                  double _val21; // required
                  _key20 = iprot.readString();
                  _val21 = iprot.readDouble();
                  struct.doubleMetrics.put(_key20, _val21);
                }
                iprot.readMapEnd();
              }
              struct.setDoubleMetricsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // LONG_METRICS
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map22 = iprot.readMapBegin();
                struct.longMetrics = new HashMap<String,Long>(2*_map22.size);
                for (int _i23 = 0; _i23 < _map22.size; ++_i23)
                {
                  String _key24; // required
                  long _val25; // required
                  _key24 = iprot.readString();
                  _val25 = iprot.readI64();
                  struct.longMetrics.put(_key24, _val25);
                }
                iprot.readMapEnd();
              }
              struct.setLongMetricsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, DealOfferGeoSummary_t struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.dealOffer != null) {
        oprot.writeFieldBegin(DEAL_OFFER_FIELD_DESC);
        struct.dealOffer.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.isSetDistanceInMeters()) {
        oprot.writeFieldBegin(DISTANCE_IN_METERS_FIELD_DESC);
        oprot.writeDouble(struct.distanceInMeters);
        oprot.writeFieldEnd();
      }
      if (struct.isSetClosestMerchantInMeters()) {
        oprot.writeFieldBegin(CLOSEST_MERCHANT_IN_METERS_FIELD_DESC);
        oprot.writeDouble(struct.closestMerchantInMeters);
        oprot.writeFieldEnd();
      }
      if (struct.doubleMetrics != null) {
        if (struct.isSetDoubleMetrics()) {
          oprot.writeFieldBegin(DOUBLE_METRICS_FIELD_DESC);
          {
            oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.DOUBLE, struct.doubleMetrics.size()));
            for (Map.Entry<String, Double> _iter26 : struct.doubleMetrics.entrySet())
            {
              oprot.writeString(_iter26.getKey());
              oprot.writeDouble(_iter26.getValue());
            }
            oprot.writeMapEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.longMetrics != null) {
        if (struct.isSetLongMetrics()) {
          oprot.writeFieldBegin(LONG_METRICS_FIELD_DESC);
          {
            oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.I64, struct.longMetrics.size()));
            for (Map.Entry<String, Long> _iter27 : struct.longMetrics.entrySet())
            {
              oprot.writeString(_iter27.getKey());
              oprot.writeI64(_iter27.getValue());
            }
            oprot.writeMapEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DealOfferGeoSummary_tTupleSchemeFactory implements SchemeFactory {
    public DealOfferGeoSummary_tTupleScheme getScheme() {
      return new DealOfferGeoSummary_tTupleScheme();
    }
  }

  private static class DealOfferGeoSummary_tTupleScheme extends TupleScheme<DealOfferGeoSummary_t> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, DealOfferGeoSummary_t struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      struct.dealOffer.write(oprot);
      BitSet optionals = new BitSet();
      if (struct.isSetDistanceInMeters()) {
        optionals.set(0);
      }
      if (struct.isSetClosestMerchantInMeters()) {
        optionals.set(1);
      }
      if (struct.isSetDoubleMetrics()) {
        optionals.set(2);
      }
      if (struct.isSetLongMetrics()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetDistanceInMeters()) {
        oprot.writeDouble(struct.distanceInMeters);
      }
      if (struct.isSetClosestMerchantInMeters()) {
        oprot.writeDouble(struct.closestMerchantInMeters);
      }
      if (struct.isSetDoubleMetrics()) {
        {
          oprot.writeI32(struct.doubleMetrics.size());
          for (Map.Entry<String, Double> _iter28 : struct.doubleMetrics.entrySet())
          {
            oprot.writeString(_iter28.getKey());
            oprot.writeDouble(_iter28.getValue());
          }
        }
      }
      if (struct.isSetLongMetrics()) {
        {
          oprot.writeI32(struct.longMetrics.size());
          for (Map.Entry<String, Long> _iter29 : struct.longMetrics.entrySet())
          {
            oprot.writeString(_iter29.getKey());
            oprot.writeI64(_iter29.getValue());
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, DealOfferGeoSummary_t struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.dealOffer = new DealOffer_t();
      struct.dealOffer.read(iprot);
      struct.setDealOfferIsSet(true);
      BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.distanceInMeters = iprot.readDouble();
        struct.setDistanceInMetersIsSet(true);
      }
      if (incoming.get(1)) {
        struct.closestMerchantInMeters = iprot.readDouble();
        struct.setClosestMerchantInMetersIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TMap _map30 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.DOUBLE, iprot.readI32());
          struct.doubleMetrics = new HashMap<String,Double>(2*_map30.size);
          for (int _i31 = 0; _i31 < _map30.size; ++_i31)
          {
            String _key32; // required
            double _val33; // required
            _key32 = iprot.readString();
            _val33 = iprot.readDouble();
            struct.doubleMetrics.put(_key32, _val33);
          }
        }
        struct.setDoubleMetricsIsSet(true);
      }
      if (incoming.get(3)) {
        {
          org.apache.thrift.protocol.TMap _map34 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.I64, iprot.readI32());
          struct.longMetrics = new HashMap<String,Long>(2*_map34.size);
          for (int _i35 = 0; _i35 < _map34.size; ++_i35)
          {
            String _key36; // required
            long _val37; // required
            _key36 = iprot.readString();
            _val37 = iprot.readI64();
            struct.longMetrics.put(_key36, _val37);
          }
        }
        struct.setLongMetricsIsSet(true);
      }
    }
  }

}

