/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.talool.api.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum LinkType implements org.apache.thrift.TEnum {
  MERCHANT(0),
  DEAL(1),
  DEAL_OFFER(2),
  GIFT(3),
  CUSTOMER(4),
  DEAL_ACQUIRE(5),
  MERCHANT_LOCATION(6),
  EXTERNAL(7);

  private final int value;

  private LinkType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static LinkType findByValue(int value) { 
    switch (value) {
      case 0:
        return MERCHANT;
      case 1:
        return DEAL;
      case 2:
        return DEAL_OFFER;
      case 3:
        return GIFT;
      case 4:
        return CUSTOMER;
      case 5:
        return DEAL_ACQUIRE;
      case 6:
        return MERCHANT_LOCATION;
      case 7:
        return EXTERNAL;
      default:
        return null;
    }
  }
}
