/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.talool.api.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class MerchantsResponse_t implements org.apache.thrift.TBase<MerchantsResponse_t, MerchantsResponse_t._Fields>, java.io.Serializable, Cloneable, Comparable<MerchantsResponse_t> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MerchantsResponse_t");

  private static final org.apache.thrift.protocol.TField MERCHANTS_FIELD_DESC = new org.apache.thrift.protocol.TField("merchants", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new MerchantsResponse_tStandardSchemeFactory());
    schemes.put(TupleScheme.class, new MerchantsResponse_tTupleSchemeFactory());
  }

  public List<com.talool.api.thrift.Merchant_t> merchants; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MERCHANTS((short)1, "merchants");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MERCHANTS
          return MERCHANTS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private _Fields optionals[] = {_Fields.MERCHANTS};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MERCHANTS, new org.apache.thrift.meta_data.FieldMetaData("merchants", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, com.talool.api.thrift.Merchant_t.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MerchantsResponse_t.class, metaDataMap);
  }

  public MerchantsResponse_t() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MerchantsResponse_t(MerchantsResponse_t other) {
    if (other.isSetMerchants()) {
      List<com.talool.api.thrift.Merchant_t> __this__merchants = new ArrayList<com.talool.api.thrift.Merchant_t>(other.merchants.size());
      for (com.talool.api.thrift.Merchant_t other_element : other.merchants) {
        __this__merchants.add(new com.talool.api.thrift.Merchant_t(other_element));
      }
      this.merchants = __this__merchants;
    }
  }

  public MerchantsResponse_t deepCopy() {
    return new MerchantsResponse_t(this);
  }

  public void clear() {
    this.merchants = null;
  }

  public int getMerchantsSize() {
    return (this.merchants == null) ? 0 : this.merchants.size();
  }

  public java.util.Iterator<com.talool.api.thrift.Merchant_t> getMerchantsIterator() {
    return (this.merchants == null) ? null : this.merchants.iterator();
  }

  public void addToMerchants(com.talool.api.thrift.Merchant_t elem) {
    if (this.merchants == null) {
      this.merchants = new ArrayList<com.talool.api.thrift.Merchant_t>();
    }
    this.merchants.add(elem);
  }

  public List<com.talool.api.thrift.Merchant_t> getMerchants() {
    return this.merchants;
  }

  public MerchantsResponse_t setMerchants(List<com.talool.api.thrift.Merchant_t> merchants) {
    this.merchants = merchants;
    return this;
  }

  public void unsetMerchants() {
    this.merchants = null;
  }

  /** Returns true if field merchants is set (has been assigned a value) and false otherwise */
  public boolean isSetMerchants() {
    return this.merchants != null;
  }

  public void setMerchantsIsSet(boolean value) {
    if (!value) {
      this.merchants = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case MERCHANTS:
      if (value == null) {
        unsetMerchants();
      } else {
        setMerchants((List<com.talool.api.thrift.Merchant_t>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case MERCHANTS:
      return getMerchants();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case MERCHANTS:
      return isSetMerchants();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof MerchantsResponse_t)
      return this.equals((MerchantsResponse_t)that);
    return false;
  }

  public boolean equals(MerchantsResponse_t that) {
    if (that == null)
      return false;

    boolean this_present_merchants = true && this.isSetMerchants();
    boolean that_present_merchants = true && that.isSetMerchants();
    if (this_present_merchants || that_present_merchants) {
      if (!(this_present_merchants && that_present_merchants))
        return false;
      if (!this.merchants.equals(that.merchants))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(MerchantsResponse_t other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetMerchants()).compareTo(other.isSetMerchants());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMerchants()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.merchants, other.merchants);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("MerchantsResponse_t(");
    boolean first = true;

    if (isSetMerchants()) {
      sb.append("merchants:");
      if (this.merchants == null) {
        sb.append("null");
      } else {
        sb.append(this.merchants);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te.getMessage());
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te.getMessage());
    }
  }

  private static class MerchantsResponse_tStandardSchemeFactory implements SchemeFactory {
    public MerchantsResponse_tStandardScheme getScheme() {
      return new MerchantsResponse_tStandardScheme();
    }
  }

  private static class MerchantsResponse_tStandardScheme extends StandardScheme<MerchantsResponse_t> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, MerchantsResponse_t struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MERCHANTS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                struct.merchants = new ArrayList<com.talool.api.thrift.Merchant_t>(_list8.size);
                for (int _i9 = 0; _i9 < _list8.size; ++_i9)
                {
                  com.talool.api.thrift.Merchant_t _elem10;
                  _elem10 = new com.talool.api.thrift.Merchant_t();
                  _elem10.read(iprot);
                  struct.merchants.add(_elem10);
                }
                iprot.readListEnd();
              }
              struct.setMerchantsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, MerchantsResponse_t struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.merchants != null) {
        if (struct.isSetMerchants()) {
          oprot.writeFieldBegin(MERCHANTS_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.merchants.size()));
            for (com.talool.api.thrift.Merchant_t _iter11 : struct.merchants)
            {
              _iter11.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MerchantsResponse_tTupleSchemeFactory implements SchemeFactory {
    public MerchantsResponse_tTupleScheme getScheme() {
      return new MerchantsResponse_tTupleScheme();
    }
  }

  private static class MerchantsResponse_tTupleScheme extends TupleScheme<MerchantsResponse_t> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MerchantsResponse_t struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetMerchants()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetMerchants()) {
        {
          oprot.writeI32(struct.merchants.size());
          for (com.talool.api.thrift.Merchant_t _iter12 : struct.merchants)
          {
            _iter12.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MerchantsResponse_t struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.merchants = new ArrayList<com.talool.api.thrift.Merchant_t>(_list13.size);
          for (int _i14 = 0; _i14 < _list13.size; ++_i14)
          {
            com.talool.api.thrift.Merchant_t _elem15;
            _elem15 = new com.talool.api.thrift.Merchant_t();
            _elem15.read(iprot);
            struct.merchants.add(_elem15);
          }
        }
        struct.setMerchantsIsSet(true);
      }
    }
  }

}

